module.exports = {
  userMsg: {
    signUp: "Registartion Successfully",
    signIn: "Log-In Successfully",
    getProfile: "Profile Fetched Successfully",
    changeProfileImage: "Change Profile Picture Successfully",
    applyLeave: "Successfully Applyed For Leave",
    leaveApproved: "Your Leave is Approved",
    leaveRejected: "Your Leave is Rejected",
    updateMsg: "Profile Update Successfully",
    deleteMsg: "Profile Delete Successfully",
    otpSend: "Successfully Send Verification Code",
    trueOtp: "OTP Verified Successfully!",
    resetPassword:
      "Success! Your password has been reset. You can now log in with your new password.",
    GoogleLoginUser: "Google Login successfully !",
  },
  productMsg: {
    createProduct: "Successfully create a product",
    updateProduct: "Product Update Successfully",
    deleteProduct: "Product Delete Successfully",
  },
  saleMsg: {
    createSale: "Successfully create a product",
  },
  errorMsg: {
    userAlreadyExicts: "User Already Exicts",
    imageRequired: "Image is Required",
    fieldRequired: "Please Enter Required Fields",
    userNotFound: "User Not Found",
    invalidCredintial: "Invalid Credintial",
    tokenNotFound: "Token Not Found",
    unAuthorizedUser: "Unauthorized User",
    notUpdate: "Not Updated",
    noLeave: "Leave Not Found",
    onlyAdmin: "Only Admin Can Add Data",
    dataNotFound: "Data Not Found",
    notShow: "You Can't See Data",
    wrongOtp: "Please verify and enter the correct one",
    notApplyForLeave: "Your Availble Leave is 0",
    badRequest: "Bad Request",
    invalidStatus: "You Status Must Be Pending or Approved or Rejected",
  },
};
